name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
